apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: taskflow
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_USER: taskflow
  DB_NAME: taskflow
  JWT_EXPIRES_IN: 24h
  CORS_ORIGIN: "*"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: taskflow
type: Opaque
stringData:
  POSTGRES_PASSWORD: y2izFik82VEJOLK9j9ZWkD6m
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: taskflow
type: Opaque
stringData:
  DB_PASSWORD: y2izFik82VEJOLK9j9ZWkD6m
  JWT_SECRET: 6bdf49f6db692406cca72794847c02e166d4ead54bfd4f4b596f5cfcc8e09153
