apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: taskflow
data:
  APP_COLOR: blue
  BACKEND_URL: http://backend:3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: taskflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: modovar/taskflow-frontend:1.1.1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: frontend-config
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
